name: CI – Format & Lint & Complexity

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality:
    name: 代碼品質檢查
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: ⚙️ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📂 Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install isort black autoflake pylint radon

      - name: 🐚 Init Packages
        run: |
          ./init_packages.sh

      - name: 🔧 Auto Format & Clean
        run: |
          ./format_and_lint_fix.sh

      - name: 🔍 Run Pylint
        run: |
          pylint api/ --exit-zero

      - name: 📊 Run Radon Complexity
        run: |
          radon cc -s api/
